version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: abduz-postgres
    environment:
      POSTGRES_USER: abduz
      POSTGRES_PASSWORD: lDM6F1M&{IVtKi5If]R9
      POSTGRES_DB: abduz
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
